fix: Correct location flag issue when publishing
mParticle/mparticle-apple-sdk pull request #180
Opened 2023-01-30 16:16 UTC by BrandonStalnaker

## Summary
  - These commits give two options for the issue where clients attempts at publishing are triggering the NSLocationAlwaysAndWhenInUsageDescription flag from Apple. The first commit expands the pre processor flag to a CLLocation call that was not included before. The second commit removes all uses of CLLocation. When reviewing please give your opinion on which is the preferred solution.

 ## Testing Plan
 - Both commits tested on simulator to confirm no crash or issue in that respect

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-4997

2023-02-03 14:56 UTC, einsteinx2 commented
So looking over this, I think the solution should be somewhere in the middle. Basically if you take the second commit, but instead of deleting all the lines, take each deleted portion (including the entire `MPLocationManager.h/m` files) and wrap each in `#ifndef MPARTICLE_LOCATION_DISABLE`. So basically the same approach we're currently taking, but more aggressive to completely remove the location tracking code when `MPARTICLE_LOCATION_DISABLE` is specified.

2023-02-03 14:59 UTC, einsteinx2 commented
I think the problem the customer is having is related to Apple being more aggressive in it's auto-detection and probably tripping up on some other bit of code we're not removing. So if we just use the existing flag to really remove everything location related, we should be good.

2023-02-06 16:16 UTC, einsteinx2 requested changes

2023-02-06 16:16 UTC, einsteinx2 commented on mParticle-Apple-SDK/Include/mParticle.h
>   */
Should we move the ifndef to above this comment (right under the `#if TARGET_OS_IOS = 1` line) to exclude this option entirely? Or would that cause other problems? I assume right now it just won't do anything if location is disabled?

2023-02-06 16:16 UTC, einsteinx2 commented on mParticle-Apple-SDK/Utils/MPCurrentState.m
> +    BOOL gpsState = false;
```suggestion
    BOOL gpsState = NO;
```
Just for consistency in Obj-C this should probably be `NO` instead of `false`.

2023-02-06 16:16 UTC, einsteinx2 commented on mParticle-Apple-SDK/mParticle.m
> +    MPILogDebug(@"Automatic background tracking has been disabled to support users excluding location services from their applications.");
Ahh ok I see what you did. We can probably just leave this option in then.

2023-02-06 17:53 UTC, einsteinx2 approved these changes
Tested locally and confirmed complete removal of all CoreLocation related code in a test app using `strings` tool. This should be good to go. Not sure what else we could possibly remove at this point to make Apple any happier...

2023-02-06 18:46 UTC, merged

2023-02-07 20:57 UTC, mparticle-automation commented
:tada: This PR is included in version 8.11.1 :tada:

The release is available on [GitHub release](https://github.com/mParticle/mparticle-apple-sdk/releases/tag/v8.11.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-08 18:28 UTC, eseay commented
@einsteinx2 I noticed in this change that you updated the README to include instructions about how to set this flag using CocoaPods. Is there a way to make this work if we integration mParticle via SPM?