refactor: Port MPListenerController to Swift
mParticle/mparticle-apple-sdk pull request #320
Opened 2024-12-16 20:20 UTC by BrandonStalnaker

## Summary
 - Refacotr MPListenerController and MPListenerProtocol to Swift

 ## Testing Plan
 - Tested using sample app

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-6730

2025-01-06 19:20 UTC, einsteinx2 requested changes

2025-01-06 19:20 UTC, einsteinx2 commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +@objc public enum MPEndpoint: Int {
Let's move these 2 enums and the MPListenerProtocol into a dedicated `MPListenerProtocol.swift` file

2025-01-06 19:20 UTC, einsteinx2 commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +        self.sdkListeners.append(sdkListener)
```suggestion
        sdkListeners.append(sdkListener)
```

Per style guide, let's get rid of these explicit `self.` calls in

2025-01-06 19:20 UTC, einsteinx2 commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +        self.sdkListeners = self.sdkListeners.filter { sdkListener !== $0 }
```suggestion
        sdkListeners = sdkListeners.filter { sdkListener !== $0 }
```

2025-01-06 19:20 UTC, einsteinx2 commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +    case attributes = 0, breadcrumbs, messages, reporting, sessions, uploads, unknown
This style is fine for now, but let's discuss later if we want to use this style or enforce a more classic "every item on it's own line" style.

2025-01-06 19:20 UTC, einsteinx2 commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +        self.sdkListeners = self.sdkListeners.filter { sdkListener !== $0 }
Another thing, this actually has different behavior than the original Obj-C code due to the use of the `!==` identity equality operator. The original `removeObject:` call in Obj-C will use the `isEqual:` method to compare objects, which is essentially equivalent to `==` in Swift, but you're using the `===` form here (or well the negative `!==` form vs `!=`) which checks for address equality, i.e. exact same object.

In this case it may not matter, but was this intentional?

2025-01-06 19:20 UTC, einsteinx2 commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +            let stackTrace = [Thread.callStackSymbols]
```suggestion
            let stackTrace = Thread.callStackSymbols
```

This has different behavior from the original Obj-C. The `Thread.callStackSymbols` method returns an array (`[String]`) already, so this is putting an array inside another array.

2025-01-06 19:20 UTC, einsteinx2 commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +            let stackTrace = [Thread.callStackSymbols]
```suggestion
            let stackTrace = Thread.callStackSymbols
```

2025-01-06 19:20 UTC, einsteinx2 commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +                parameters.append(parameter1!)
```suggestion
            if let parameter1 = parameter1 {
                parameters.append(parameter1)
```

All of these nil checks should be replaced with `if let` and all uses of the `!` operator removed.

2025-01-06 19:20 UTC, einsteinx2 commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +    @objc optional func onAPICalled(_ apiName: Any!, stackTrace: Any!, isExternal: Any!, objects: Any!)
I assume the `!`'s here are to keep the same public interface as before?

2025-01-06 19:20 UTC, einsteinx2 commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +        for delegate in self.sdkListeners {
```suggestion
        for delegate in sdkListeners {
```

All of these explicit calls to self should be removed per the style guide

2025-01-06 19:20 UTC, einsteinx2 commented
Also I notice this doesn't seem to be used in any tests? We should add some before merging this.

2025-01-22 18:00 UTC, BrandonStalnaker commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +        self.sdkListeners = self.sdkListeners.filter { sdkListener !== $0 }
It was intentional because an array of this type [MPListenerProtocol] doesn't have any properties to compare so I had to check for adress (basically == is not valid for comparing 2 MPListenerProtocol conforming objects in swift)

2025-01-22 18:04 UTC, BrandonStalnaker commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +    @objc optional func onAPICalled(_ apiName: Any!, stackTrace: Any!, isExternal: Any!, objects: Any!)
yep line 43 of mParticle-Apple-SDK/Include/MPListenerProtocol.h

2025-01-22 21:01 UTC, einsteinx2 requested changes

2025-01-22 21:01 UTC, einsteinx2 commented on mParticle-Apple-SDK/Listener/MPListenerController.swift
> +            if parameter1 != nil {
```suggestion
            if let parameter1 = parameter1 {
```

2025-01-22 21:11 UTC, einsteinx2 approved these changes

2025-01-22 21:12 UTC, merged