refactor: Port MPLaunchInfo to Swift
mParticle/mparticle-apple-sdk pull request #321
Opened 2024-12-19 20:21 UTC by BrandonStalnaker

## Summary
 - Refactored the MPLaunchInfo class to swift

 ## Testing Plan
 - Ran in sample app and confirmed existing unit tests

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-6986

2025-01-06 19:28 UTC, einsteinx2 requested changes

2025-01-06 19:28 UTC, einsteinx2 commented on mParticle-Apple-SDK/Utils/MPLaunchInfo.swift
> +        guard let url else { return nil }
Just a note for discussion later to add to the style guide, but I personally really like single line guard statements like this. I think I've been doing them elsewhere with new lines like this:

```
guard let url else { 
    return nil 
}
```

But I was only doing that because we tended to not use single line statements in other places, but I would love to discuss this and add something official to the style guide about it.

2025-01-06 19:28 UTC, einsteinx2 commented on mParticle-Apple-SDK/Utils/MPLaunchInfo.swift
> +        }
```suggestion
        if let sourceApplication = self.sourceApplication {
            self.options?[UIApplication.OpenURLOptionsKey.sourceApplication.rawValue] = sourceApplication
        }
        if let annotation = self.annotation {
            self.options?[UIApplication.OpenURLOptionsKey.annotation.rawValue] = annotation
        }
```

2025-01-06 19:28 UTC, einsteinx2 commented on mParticle-Apple-SDK/Utils/MPLaunchInfo.swift
> +                if let valueString = self.convertAnnotationToString(rawAnnotation: value) {
```suggestion
                if let valueString = convertAnnotationToString(rawAnnotation: value) {
```

2025-01-06 19:28 UTC, einsteinx2 commented on mParticle-Apple-SDK/Utils/MPLaunchInfo.swift
> +                if let valueString = self.convertAnnotationToString(rawAnnotation: value) {
```suggestion
                if let valueString = convertAnnotationToString(rawAnnotation: value) {
```

2025-01-06 19:28 UTC, einsteinx2 commented on mParticle-Apple-SDK/Utils/MPLaunchInfo.swift
> +            }
```suggestion
            if finalArray.isEmpty { 
                return nil 
            } else {
                return serializeObject(finalArray)
            }
```

I'm all for the single line guard statements, but I think should be on separate lines for readability.

2025-01-06 19:28 UTC, einsteinx2 commented on mParticle-Apple-SDK/Utils/MPLaunchInfo.swift
> +            }
```suggestion
            return finalArray.isEmpty ? nil : serializeObject(finalArray)
```

Or actually even better, why not a ternary operator (if Swift allows it) in this case?

2025-01-22 18:19 UTC, BrandonStalnaker commented on mParticle-Apple-SDK/Utils/MPLaunchInfo.swift
> +            }
tested to confirm and yeah works fine

2025-01-22 21:04 UTC, einsteinx2 approved these changes

2025-01-22 21:13 UTC, merged